name: Nuxt3 to Github Pages
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20  # Adjust as needed
      - name: Change Working Dir
        working-directory: ./d2ther
      - name: Deploy
        uses: khanshifaul/NuxtPagesAction@0.0.3
        with:
          useyarn: true
          username: D2theR 
          reponame: D2theR
          token: ${{ secrets.NUXT_KEY }}
          
