name: Nuxt3 to Github Pages
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20  # Adjust as needed
      - run: cd d2ther && yarn install # Or 'yarn install' if useyarn is true
      - run: nuxt generate
      - name: Deploy
        uses: khanshifaul/NuxtPagesAction@0.0.3
        with:
          username: D2theR 
          reponame: D2theR
          token: ${{ secrets.NUXT_KEY }}
          useyarn: true
